config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :scores
  resources :positions
  resources :magazines
  resources :enologists
  resources :wines
  resources :assemblies
  resources :strains
  root "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enologist.rb
class Enologist < ApplicationRecord
  has_many :positions
  has_many :magazines,  through: :positions
  has_many :scores
  has_many :wines,  through: :scores

  def to_s
    name
  end

  def work_in
    magazine_ids  
  end
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: [:show, :edit, :update, :destroy]

  # GET /enologists
  # GET /enologists.json
  def index
    @enologists = Enologist.all.order(:age)
  end

  # GET /enologists/1
  # GET /enologists/1.json
  def show
  end

  # GET /enologists/new
  def new
    @enologist = Enologist.new
  end

  # GET /enologists/1/edit
  def edit
  end

  # POST /enologists
  # POST /enologists.json
  def create
    @enologist = Enologist.new(enologist_params)

    respond_to do |format|
      if @enologist.save
        format.html { redirect_to @enologist, notice: 'Enologist was successfully created.' }
        format.json { render :show, status: :created, location: @enologist }
      else
        format.html { render :new }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologists/1
  # PATCH/PUT /enologists/1.json
  def update
    respond_to do |format|
      if @enologist.update(enologist_params)
        format.html { redirect_to @enologist, notice: 'Enologist was successfully updated.' }
        format.json { render :show, status: :ok, location: @enologist }
      else
        format.html { render :edit }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologists/1
  # DELETE /enologists/1.json
  def destroy
    @enologist.destroy
    respond_to do |format|
      format.html { redirect_to enologists_url, notice: 'Enologist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:name, :age, :nationality, 
      positions_attributes[:magazine_id, :name, :enologist_id])
    end
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/views/enologists/_form.html.erb
<%= form_with(model: enologist, local: true) do |form| %>
  <% if enologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
      <% enologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enologists/edit.html.erb
<h1>Editing Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Show', @enologist %> |
<%= link_to 'Back', enologists_path %>

app/views/enologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre completo</th>
      <th>Edad</th>
      <th>Nacionalidad</th>
      <th>Trabaja en</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologists.each do |enologist| %>
      <tr>
        <td><%= enologist.name %></td>
        <td><%= enologist.age %></td>
        <td><%= enologist.nationality %></td>
        <td><%= enologist.work_in %></td>
        <td><%= link_to 'Show', enologist %></td>
        <td><%= link_to 'Edit', edit_enologist_path(enologist) %></td>
        <td><%= link_to 'Destroy', enologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologist', new_enologist_path %>

app/views/enologists/new.html.erb
<h1>New Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Back', enologists_path %>

app/views/enologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologist.name %>
</p>

<%= link_to 'Edit', edit_enologist_path(@enologist) %> |
<%= link_to 'Back', enologists_path %>