config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :scores
  resources :positions
  resources :magazines
  resources :enologists
  resources :wines
  resources :assemblies
  resources :strains
  root "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  belongs_to :wine
  belongs_to :strain

  def strain_name
    strain.name
  end

  def to_s
    name
  end

end

app/models/enologist.rb
class Enologist < ApplicationRecord
  has_many :positions
  has_many :magazines,  through: :positions
  has_many :scores
  has_many :wines,  through: :scores

  def to_s
    name
  end

  def work_in
    magazine_ids  
  end
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_many :positions
  has_many :enologists,  through: :positions

  def to_s
    name
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :enologist
  belongs_to :magazine

  def to_s
    name
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :wine
  belongs_to :enologist

  def enologist_name
    enologist.name
  end

end

app/models/strain.rb
class Strain < ApplicationRecord
  has_many :assemblies
  has_many :wines,  through: :assemblies
  
  validates :name, presence: true
  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :assemblies
  has_many :strains,  through: :assemblies
  has_many :scores
  has_many :enologists, through: :scores

  accepts_nested_attributes_for :assemblies
  accepts_nested_attributes_for :scores
  accepts_nested_attributes_for :enologists

  def to_s
    name
  end

  def strains_detail
    detail = assemblies.map do |assembly|
      "#{assembly.strain_name} (#{assembly.percentage}%)"
    end
    detail.sort.join(", ")
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
    @enologists = Enologist.all.order(:age)
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:grade, :wine_id, :enologist_id)
    end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: [:show, :edit, :update, :destroy]

  # GET /strains
  # GET /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1
  # GET /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    redirect_to wines_path unless current_user&.admin?
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains
  # POST /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to @strain, notice: 'Strain was successfully created.' }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1
  # PATCH/PUT /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to @strain, notice: 'Strain was successfully updated.' }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1
  # DELETE /strains/1.json
  def destroy
    @strain.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: 'Strain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
    @scores = Score.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    redirect_to wines_path unless current_user&.admin?
    @wine = Wine.new
    @strains = Strain.all
    @enologists = Enologist.all.order(:age)
    @scores = Score.all
    @strains.each do |strain|
      @wine.assemblies.build(strain: strain)
    end
    
    #IDEAS PARA GUARDAR SCORE EN EDIT
    #@score = @wine.scores.build(grade: grade)
    ##@score = @wine.scores.create(:grade=> grade)
    #@wine.scores <<  Score.new(grade: grade)
    #@score.save
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)
    
    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :price, :score_id,
      assemblies_attributes: [:id,:strain_id, :wine_id, :percentage],
      scores_attributes: [:id, :enologist_id, :grade, :wine_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinos y más</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">     
  <a class="navbar-brand  style="color: white">
    <h3>Wines and more!</h3>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Ver enólogos', enologists_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Ingresar vino', new_wine_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Ingresar cepa', new_strain_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>